/**
 * Special character byte values by name
 */
export const CHARS = Object.freeze({
  ARROW_UP: '\x00',
  ARROW_DOWN: '\x01',
  LINES: '\x02',
  SWITCH_LEFT: '\x03',
  SWITCH_RIGHT: '\x04',
  SWITCH_BOTH: '\x05',
  SWITCH_NONE: '\x06',
  FOLDER: '\x07',
  BROKEN_BAR: '\x08',
  DEGREE: '\x09',
  A_UMLAUT_CAPITAL: '\x0A',
  C_CEDILLA_CAPITAL: '\x0B',
  O_UMLAUT_CAPITAL: '\x0C',
  U_UMLAUT_CAPITAL: '\x0D',
  S_SHARP: '\x0E',
  A_GRAVE: '\x0F',
  A_UMLAUT: '\x10',
  C_CEDILLA: '\x11',
  E_GRAVE: '\x12',
  E_ACUTE: '\x13',
  E_CIRCUMFLEX: '\x14',
  I_CIRCUMFLEX: '\x15',
  N_TILDE: '\x16',
  O_UMLAUT: '\x17',
  DIVISION: '\x18',
  O_STROKE: '\x19',
  U_UMLAUT: '\x1A',
  FLAT: '\x1B',
  ELLIPSES: '\x1C',
  BOX: '\x1D',
  ARROW_RIGHT: '\x1E',
  ARROW_LEFT: '\x1F',
  TRIANGLE: '\x7F'
});

/**
 * Mapping from unicode chars to corresponding Push byte value.
 */
export const MAPPING = Object.freeze({
  '↑': 0,
  '↓': 1,
  '≡': 2,
  '┣': 3,
  '┫': 4,
  '║': 5,
  '╍': 6,
  '⏍': 7,
  '¦': 8,
  '°': 9,
  'Ä': 10,
  'Ç': 11,
  'Ö': 12,
  'Ü': 13,
  'ß': 14,
  'à': 15,
  'ä': 16,
  'ç': 17,
  'è': 18,
  'é': 19,
  'ê': 20,
  'î': 21,
  'ñ': 22,
  'ö': 23,
  '÷': 24,
  'ø': 25,
  'ü': 26,
  '♭': 27,
  '…': 28,
  '█': 29,
  '→': 30,
  '←': 31,
  '▶': 127
});
